disabled_rules: # rule identifiers to exclude from running
  - line_length
  - trailing_whitespace
  - file_length
  - trailing_comma
  - cyclomatic_complexity
  - nesting
  - function_body_length
  - xctfail_message
  - function_parameter_count
  - large_tuple
  - switch_case_alignment
  - valid_ibinspectable
opt_in_rules: # some rules are only opt-in
  - implicit_return
  - explicit_self
  - closure_spacing
  - array_init
  - attributes
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - first_where
  - last_where
  - multiline_arguments
  - multiline_function_chains
  - multiline_parameters
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  
custom_rules:
  period_before_enum_cases:
    regex: "(\\. )"
    match_kinds:
      - identifier
      - keyword
      - argument

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
implicit_return:
  included: [getter]
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
# they can set both implicitly with an array
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown)
